name: Build UniApp — Android / iOS / 微信小程序

on:
  push:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      platforms:
        description: "构建平台（逗号分隔，可选: android,ios,mp-weixin）"
        required: false
        default: "android,mp-weixin"

env:
  NODE_VERSION: '18'
  PNPM_VERSION: 'latest'

jobs:
  # ═══════════════════════════════════════════════════════════
  # JOB 1 ▸ 微信小程序
  # ═══════════════════════════════════════════════════════════
  build-mp-weixin:
    name: 微信小程序
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}

      - uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: ${{ runner.os }}-pnpm-

      - name: Resolve @dcloudio version & install
        run: |
          npm config set registry https://registry.npmmirror.com

          DCLOUDIO_VER=$(npm view @dcloudio/vite-plugin-uni versions --json 2>/dev/null | \
            node -e "
            let raw = '';
            process.stdin.on('data', d => raw += d);
            process.stdin.on('end', () => {
              try {
                const vs = JSON.parse(raw);
                const dated = vs.filter(v => /^3\.0\.0-\d{13,}$/.test(v));
                if (dated.length) {
                  dated.sort((a, b) => {
                    const na = BigInt(a.split('-')[1]);
                    const nb = BigInt(b.split('-')[1]);
                    return na < nb ? -1 : na > nb ? 1 : 0;
                  });
                  console.log(dated[dated.length - 1]);
                } else {
                  console.log('3.0.0-3090820231023001');
                }
              } catch(e) {
                console.log('3.0.0-3090820231023001');
              }
            });
            " || echo "3.0.0-3090820231023001")

          echo "📌 @dcloudio resolved: ${DCLOUDIO_VER}"

          node -e "
          const fs = require('fs');
          const ver = process.argv[1];
          const pkg = JSON.parse(fs.readFileSync('package.json', 'utf8'));
          ['dependencies', 'devDependencies'].forEach(key => {
            if (!pkg[key]) return;
            Object.keys(pkg[key]).forEach(name => {
              if (name.startsWith('@dcloudio/') && name !== '@dcloudio/types') {
                pkg[key][name] = ver;
              }
            });
          });
          fs.writeFileSync('package.json', JSON.stringify(pkg, null, 2));
          console.log('✅ package.json @dcloudio 版本已固定为:', ver);
          " "${DCLOUDIO_VER}"

          pnpm install --no-frozen-lockfile

      - name: Build WeChat Mini Program
        run: pnpm build:mp-weixin

      - name: Verify & package output
        run: |
          if [ ! -d "dist/build/mp-weixin" ]; then
            echo "❌ dist/build/mp-weixin 未找到"; exit 1
          fi
          echo "✅ 微信小程序构建成功"
          ls -lh dist/build/mp-weixin/
          cd dist/build
          zip -r ../../mp-weixin-${{ github.sha }}.zip mp-weixin/

      - uses: actions/upload-artifact@v4
        with:
          name: mp-weixin-${{ github.sha }}
          path: mp-weixin-${{ github.sha }}.zip
          retention-days: 7

  # ═══════════════════════════════════════════════════════════
  # JOB 2 ▸ Android APK
  # ═══════════════════════════════════════════════════════════
  build-android:
    name: Android APK
    runs-on: ubuntu-latest
    timeout-minutes: 60

    env:
      DCLOUD_ANDROID_SDK_URL:  ${{ secrets.DCLOUD_ANDROID_SDK_URL }}
      DCLOUD_APPKEY:           ${{ secrets.DCLOUD_APPKEY }}
      ANDROID_KEYSTORE_BASE64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
      ANDROID_KEY_ALIAS:       ${{ secrets.ANDROID_KEY_ALIAS }}
      ANDROID_KEY_PASSWORD:    ${{ secrets.ANDROID_KEY_PASSWORD }}
      ANDROID_STORE_PASSWORD:  ${{ secrets.ANDROID_STORE_PASSWORD }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}

      - uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: ${{ runner.os }}-pnpm-

      - name: Resolve @dcloudio version & install
        run: |
          npm config set registry https://registry.npmmirror.com

          DCLOUDIO_VER=$(npm view @dcloudio/vite-plugin-uni versions --json 2>/dev/null | \
            node -e "
            let raw = '';
            process.stdin.on('data', d => raw += d);
            process.stdin.on('end', () => {
              try {
                const vs = JSON.parse(raw);
                const dated = vs.filter(v => /^3\.0\.0-\d{13,}$/.test(v));
                if (dated.length) {
                  dated.sort((a, b) => {
                    const na = BigInt(a.split('-')[1]);
                    const nb = BigInt(b.split('-')[1]);
                    return na < nb ? -1 : na > nb ? 1 : 0;
                  });
                  console.log(dated[dated.length - 1]);
                } else {
                  console.log('3.0.0-3090820231023001');
                }
              } catch(e) {
                console.log('3.0.0-3090820231023001');
              }
            });
            " || echo "3.0.0-3090820231023001")

          echo "📌 @dcloudio resolved: ${DCLOUDIO_VER}"

          node -e "
          const fs = require('fs');
          const ver = process.argv[1];
          const pkg = JSON.parse(fs.readFileSync('package.json', 'utf8'));
          ['dependencies', 'devDependencies'].forEach(key => {
            if (!pkg[key]) return;
            Object.keys(pkg[key]).forEach(name => {
              if (name.startsWith('@dcloudio/') && name !== '@dcloudio/types') {
                pkg[key][name] = ver;
              }
            });
          });
          fs.writeFileSync('package.json', JSON.stringify(pkg, null, 2));
          console.log('✅ package.json @dcloudio 版本已固定为:', ver);
          " "${DCLOUDIO_VER}"

          pnpm install --no-frozen-lockfile

      - name: Build App resources
        run: pnpm build:app

      - name: Verify app resources
        run: |
          if [ ! -d "dist/build/app" ]; then
            echo "❌ dist/build/app 未找到"; exit 1
          fi
          echo "✅ App 资源构建成功"
          ls -lh dist/build/app/

      - uses: actions/upload-artifact@v4
        with:
          name: app-resources-${{ github.sha }}
          path: dist/build/app/
          retention-days: 7

      - name: Download DCloud Android offline SDK
        if: ${{ env.DCLOUD_ANDROID_SDK_URL != '' }}
        run: |
          echo "⬇️ 下载 Android 离线 SDK..."
          curl -L -o android-sdk.zip "${{ env.DCLOUD_ANDROID_SDK_URL }}"
          unzip -q android-sdk.zip -d android-sdk
          echo "✅ SDK 解压完成"

      - name: Configure AppKey & copy app resources
        if: ${{ env.DCLOUD_ANDROID_SDK_URL != '' }}
        run: |
          APP_ID=$(python3 -c "
          import json, os
          p = 'src/manifest.json' if os.path.exists('src/manifest.json') else 'manifest.json'
          d = json.load(open(p))
          print(d.get('appid', '__UNI__APPID'))
          ")
          echo "🆔 AppID: ${APP_ID}"
          SIMPLEDEMOSRC="android-sdk/HBuilder-Integrate-AS/simpleDemo/src/main"
          WWW_DIR="${SIMPLEDEMOSRC}/assets/apps/${APP_ID}/www"
          mkdir -p "${WWW_DIR}"
          cp -r dist/build/app/. "${WWW_DIR}/"
          CTRL="${SIMPLEDEMOSRC}/assets/data/dcloud_control.xml"
          [ -f "${CTRL}" ] && sed -i "s/__APPKEY__/${{ env.DCLOUD_APPKEY }}/g" "${CTRL}"
          echo "✅ App 资源已复制"

      - name: Setup signing keystore
        if: ${{ env.ANDROID_KEYSTORE_BASE64 != '' }}
        run: |
          echo "${{ env.ANDROID_KEYSTORE_BASE64 }}" | base64 --decode \
            > android-sdk/HBuilder-Integrate-AS/simpleDemo/release.keystore
          echo "✅ Keystore 就绪"

      - uses: actions/cache@v4
        if: ${{ env.DCLOUD_ANDROID_SDK_URL != '' }}
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('android-sdk/**/*.gradle*') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: Build APK
        if: ${{ env.DCLOUD_ANDROID_SDK_URL != '' }}
        run: |
          cd android-sdk/HBuilder-Integrate-AS
          chmod +x gradlew
          ./gradlew assembleRelease \
            -Pandroid.injected.signing.store.file="$(pwd)/simpleDemo/release.keystore" \
            -Pandroid.injected.signing.store.password="${{ env.ANDROID_STORE_PASSWORD }}" \
            -Pandroid.injected.signing.key.alias="${{ env.ANDROID_KEY_ALIAS }}" \
            -Pandroid.injected.signing.key.password="${{ env.ANDROID_KEY_PASSWORD }}" \
            --no-daemon
          echo "✅ APK 构建完成"

      - name: Collect APK
        if: ${{ env.DCLOUD_ANDROID_SDK_URL != '' }}
        run: |
          mkdir -p apk-output
          find android-sdk -name "*.apk" -not -path "*/intermediates/*" \
            -exec cp {} apk-output/ \;
          ls -lh apk-output/

      - uses: actions/upload-artifact@v4
        if: ${{ env.DCLOUD_ANDROID_SDK_URL != '' }}
        with:
          name: android-apk-${{ github.sha }}
          path: apk-output/*.apk
          retention-days: 7

  # ═══════════════════════════════════════════════════════════
  # JOB 3 ▸ iOS IPA
  # ═══════════════════════════════════════════════════════════
  build-ios:
    name: iOS IPA
    runs-on: macos-latest
    timeout-minutes: 60

    env:
      DCLOUD_IOS_SDK_URL:       ${{ secrets.DCLOUD_IOS_SDK_URL }}
      DCLOUD_APPKEY:            ${{ secrets.DCLOUD_APPKEY }}
      IOS_CERTIFICATE_BASE64:   ${{ secrets.IOS_CERTIFICATE_BASE64 }}
      IOS_CERTIFICATE_PASSWORD: ${{ secrets.IOS_CERTIFICATE_PASSWORD }}
      IOS_PROVISION_BASE64:     ${{ secrets.IOS_PROVISION_BASE64 }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}

      - uses: actions/cache@v4
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: ${{ runner.os }}-pnpm-

      - name: Resolve @dcloudio version & install
        run: |
          npm config set registry https://registry.npmmirror.com

          DCLOUDIO_VER=$(npm view @dcloudio/vite-plugin-uni versions --json 2>/dev/null | \
            node -e "
            let raw = '';
            process.stdin.on('data', d => raw += d);
            process.stdin.on('end', () => {
              try {
                const vs = JSON.parse(raw);
                const dated = vs.filter(v => /^3\.0\.0-\d{13,}$/.test(v));
                if (dated.length) {
                  dated.sort((a, b) => {
                    const na = BigInt(a.split('-')[1]);
                    const nb = BigInt(b.split('-')[1]);
                    return na < nb ? -1 : na > nb ? 1 : 0;
                  });
                  console.log(dated[dated.length - 1]);
                } else {
                  console.log('3.0.0-3090820231023001');
                }
              } catch(e) {
                console.log('3.0.0-3090820231023001');
              }
            });
            " || echo "3.0.0-3090820231023001")

          echo "📌 @dcloudio resolved: ${DCLOUDIO_VER}"

          node -e "
          const fs = require('fs');
          const ver = process.argv[1];
          const pkg = JSON.parse(fs.readFileSync('package.json', 'utf8'));
          ['dependencies', 'devDependencies'].forEach(key => {
            if (!pkg[key]) return;
            Object.keys(pkg[key]).forEach(name => {
              if (name.startsWith('@dcloudio/') && name !== '@dcloudio/types') {
                pkg[key][name] = ver;
              }
            });
          });
          fs.writeFileSync('package.json', JSON.stringify(pkg, null, 2));
          console.log('✅ package.json @dcloudio 版本已固定为:', ver);
          " "${DCLOUDIO_VER}"

          pnpm install --no-frozen-lockfile

      - name: Build App resources
        run: pnpm build:app

      - name: Verify app resources
        run: |
          if [ ! -d "dist/build/app" ]; then
            echo "❌ dist/build/app 未找到"; exit 1
          fi
          echo "✅ App 资源构建成功"

      - uses: actions/upload-artifact@v4
        with:
          name: app-resources-ios-${{ github.sha }}
          path: dist/build/app/
          retention-days: 7

      - name: Download DCloud iOS offline SDK
        if: ${{ env.DCLOUD_IOS_SDK_URL != '' }}
        run: |
          curl -L -o ios-sdk.zip "${{ env.DCLOUD_IOS_SDK_URL }}"
          unzip -q ios-sdk.zip -d ios-sdk
          echo "✅ iOS SDK 解压完成"

      - name: Copy app resources to iOS project
        if: ${{ env.DCLOUD_IOS_SDK_URL != '' }}
        run: |
          APP_ID=$(python3 -c "
          import json, os
          p = 'src/manifest.json' if os.path.exists('src/manifest.json') else 'manifest.json'
          d = json.load(open(p))
          print(d.get('appid', '__UNI__APPID'))
          ")
          echo "🆔 AppID: ${APP_ID}"
          IOS_WWW="ios-sdk/HBuilder-Hello/HBuilder-Hello/Pandora/apps/${APP_ID}/www"
          mkdir -p "${IOS_WWW}"
          cp -r dist/build/app/. "${IOS_WWW}/"
          echo "✅ App 资源已复制"

      - name: Import certificate & provisioning profile
        if: ${{ env.IOS_CERTIFICATE_BASE64 != '' }}
        run: |
          CERT_PATH=$RUNNER_TEMP/cert.p12
          PP_PATH=$RUNNER_TEMP/profile.mobileprovision
          KEYCHAIN_PATH=$RUNNER_TEMP/app.keychain-db

          echo -n "${{ env.IOS_CERTIFICATE_BASE64 }}"  | base64 --decode -o "$CERT_PATH"
          echo -n "${{ env.IOS_PROVISION_BASE64 }}"    | base64 --decode -o "$PP_PATH"

          security create-keychain -p "ci_keychain_pwd" "$KEYCHAIN_PATH"
          security set-keychain-settings -lut 21600 "$KEYCHAIN_PATH"
          security unlock-keychain -p "ci_keychain_pwd" "$KEYCHAIN_PATH"
          security import "$CERT_PATH" -P "${{ env.IOS_CERTIFICATE_PASSWORD }}" \
            -A -t cert -f pkcs12 -k "$KEYCHAIN_PATH"
          security list-keychain -d user -s "$KEYCHAIN_PATH"
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp "$PP_PATH" ~/Library/MobileDevice/Provisioning\ Profiles/
          echo "✅ 证书导入完成"

      - name: Build & archive
        if: ${{ env.DCLOUD_IOS_SDK_URL != '' && env.IOS_CERTIFICATE_BASE64 != '' }}
        run: |
          cd ios-sdk/HBuilder-Hello
          xcodebuild \
            -project HBuilder-Hello.xcodeproj \
            -scheme HBuilder-Hello \
            -configuration Release \
            -archivePath "$RUNNER_TEMP/HBuilder.xcarchive" \
            archive
          echo "✅ Archive 完成"

      - name: Export IPA
        if: ${{ env.DCLOUD_IOS_SDK_URL != '' && env.IOS_CERTIFICATE_BASE64 != '' }}
        run: |
          xcodebuild -exportArchive \
            -archivePath "$RUNNER_TEMP/HBuilder.xcarchive" \
            -exportOptionsPlist "ios-sdk/HBuilder-Hello/ExportOptions.plist" \
            -exportPath "$RUNNER_TEMP/ipa"
          echo "✅ IPA 导出完成"
          ls -lh "$RUNNER_TEMP/ipa/"

      - uses: actions/upload-artifact@v4
        if: ${{ env.DCLOUD_IOS_SDK_URL != '' && env.IOS_CERTIFICATE_BASE64 != '' }}
        with:
          name: ios-ipa-${{ github.sha }}
          path: ${{ runner.temp }}/ipa/*.ipa
          retention-days: 7
